# Generated by Django 5.1.1 on 2025-05-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_cariventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cariventory',
            old_name='car_value',
            new_name='cars_value',
        ),
    ]
